version: '3'
services:
  web:
    build: .
    command: sh -c "sleep 10 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 80:8000
    networks:
      - my-network
    env_file:
      - .env

networks:
  my-network: